name: Lint Files
"on": 
    push:
        branches:
          - main
          - release/develop
    pull_request:
        branches:
          - main
          - release/develop
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
              yarn ci
              yarn run lint
